In [2]:
import pandas as pd

In [18]:
df = pd.read_csv('data/lifeex.csv')

df

,location_name,fips,year,val,upper,lower
0,United States of America,NaN,2000,76.780325,76.806569,76.751931
1,Alabama,1.0,2000,74.364763,74.569500,74.154499
2,Autauga County (Alabama),1001.0,2000,74.722384,75.317537,74.148346
3,Baldwin County (Alabama),1003.0,2000,76.726039,77.152319,76.340126
4,Barbour County (Alabama),1005.0,2000,73.993461,74.626864,73.354724
...,...,...,...,...,...,...
64195,Sweetwater County (Wyoming),56037.0,2019,78.384155,79.168522,77.691659
64196,Teton County (Wyoming),56039.0,2019,85.905597,86.943858,85.025816
64197,Uinta County (Wyoming),56041.0,2019,77.886506,78.814331,76.933296
64198,Washakie County (Wyoming),56043.0,2019,78.532334,79.581140,77.524879
64199,Weston County (Wyoming),56045.0,2019,79.568976,80.633775,78.519746

In [19]:
# drop rows with fips null
df = df.dropna(subset=['fips'])

#  convert fips from float to int
df['fips'] = df['fips'].astype(int)

/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gn/T/ipykernel_19107/3950140340.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fips'] = df['fips'].astype(int)

In [20]:
df

,location_name,fips,year,val,upper,lower
1,Alabama,1,2000,74.364763,74.569500,74.154499
2,Autauga County (Alabama),1001,2000,74.722384,75.317537,74.148346
3,Baldwin County (Alabama),1003,2000,76.726039,77.152319,76.340126
4,Barbour County (Alabama),1005,2000,73.993461,74.626864,73.354724
5,Bibb County (Alabama),1007,2000,73.187907,73.884669,72.510532
...,...,...,...,...,...,...
64195,Sweetwater County (Wyoming),56037,2019,78.384155,79.168522,77.691659
64196,Teton County (Wyoming),56039,2019,85.905597,86.943858,85.025816
64197,Uinta County (Wyoming),56041,2019,77.886506,78.814331,76.933296
64198,Washakie County (Wyoming),56043,2019,78.532334,79.581140,77.524879
64199,Weston County (Wyoming),56045,2019,79.568976,80.633775,78.519746

In [21]:
# only county
df = df[df['fips'] >= 1000]
df

,location_name,fips,year,val,upper,lower
2,Autauga County (Alabama),1001,2000,74.722384,75.317537,74.148346
3,Baldwin County (Alabama),1003,2000,76.726039,77.152319,76.340126
4,Barbour County (Alabama),1005,2000,73.993461,74.626864,73.354724
5,Bibb County (Alabama),1007,2000,73.187907,73.884669,72.510532
6,Blount County (Alabama),1009,2000,75.286080,75.833626,74.768508
...,...,...,...,...,...,...
64195,Sweetwater County (Wyoming),56037,2019,78.384155,79.168522,77.691659
64196,Teton County (Wyoming),56039,2019,85.905597,86.943858,85.025816
64197,Uinta County (Wyoming),56041,2019,77.886506,78.814331,76.933296
64198,Washakie County (Wyoming),56043,2019,78.532334,79.581140,77.524879
64199,Weston County (Wyoming),56045,2019,79.568976,80.633775,78.519746

In [27]:
df[df['location_name'].str.contains('Louisiana')]

,location_name,id,year,val,upper,lower
1143,Acadia Parish (Louisiana),22001,2000,72.976217,73.565728,72.386292
1144,Allen Parish (Louisiana),22003,2000,75.532789,76.252501,74.789939
1145,Ascension Parish (Louisiana),22005,2000,75.181170,75.722714,74.677372
1146,Assumption Parish (Louisiana),22007,2000,75.149068,75.916073,74.475684
1147,Avoyelles Parish (Louisiana),22009,2000,73.166983,73.738487,72.554965
...,...,...,...,...,...,...
62192,Webster Parish (Louisiana),22119,2019,73.869765,74.492653,73.220604
62193,West Baton Rouge Parish (Louisiana),22121,2019,76.877497,77.685973,76.045770
62194,West Carroll Parish (Louisiana),22123,2019,74.571939,75.523253,73.679003
62195,West Feliciana Parish (Louisiana),22125,2019,77.259754,78.203036,76.380491
62196,Winn Parish (Louisiana),22127,2019,74.757767,75.618779,73.959499

In [24]:
# rename fips to id
df.rename(columns={'fips': 'id'}, inplace=True)
df

/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gn/T/ipykernel_19107/2795662788.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'fips': 'id'}, inplace=True)

In [25]:
df.to_csv('data/lifeex.csv', index=False)