<a href="https://colab.research.google.com/github/gmelmed/gmelmed.github.io/blob/main/cc8_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I. Loading in prices data

In [2]:
import pandas as pd

In [9]:
# Add a progress bar to the reading process
prices_df = pd.read_csv('https://eco-prices-scrapes.s3.eu-west-2.amazonaws.com/teaching/davies_price_data/db_prices.csv')

prices_df

,quote_date,shop_code,item_id_raw,region,price,indicator_box,item_id
0,199108.0,2.0,210101,2.0,0.49000,NaN,210101
1,199007.0,10.0,210101,11.0,0.52000,NaN,210101
2,199007.0,2.0,210101,12.0,0.37000,NaN,210101
3,199811.0,179.0,210101,8.0,0.69000,NaN,210101
4,199108.0,1.0,210101,10.0,0.47000,NaN,210101
...,...,...,...,...,...,...,...
46689338,200704.0,441.0,640406,4.0,55.00000,NaN,640406
46689339,200701.0,731.0,640406,3.0,85.00000,NaN,640406
46689340,201210.0,5074.0,640406,3.0,40.00000,NaN,640406
46689341,200812.0,542.0,640406,2.0,45.00000,NaN,640406
46689342,202312.0,5084.0,640406,3.0,183.99001,NaN,640406

In [10]:
prices_df

,quote_date,shop_code,item_id_raw,region,price,indicator_box,item_id
0,199108.0,2.0,210101,2.0,0.49000,NaN,210101
1,199007.0,10.0,210101,11.0,0.52000,NaN,210101
2,199007.0,2.0,210101,12.0,0.37000,NaN,210101
3,199811.0,179.0,210101,8.0,0.69000,NaN,210101
4,199108.0,1.0,210101,10.0,0.47000,NaN,210101
...,...,...,...,...,...,...,...
46689338,200704.0,441.0,640406,4.0,55.00000,NaN,640406
46689339,200701.0,731.0,640406,3.0,85.00000,NaN,640406
46689340,201210.0,5074.0,640406,3.0,40.00000,NaN,640406
46689341,200812.0,542.0,640406,2.0,45.00000,NaN,640406
46689342,202312.0,5084.0,640406,3.0,183.99001,NaN,640406

In [11]:
items_df = pd.read_csv('https://eco-prices-scrapes.s3.eu-west-2.amazonaws.com/teaching/davies_price_data/db_item_clean.csv')

items_df

,item_id,description,date_quote_s,date_quote_e,n_obs
0,210101,LARGE LOAF-WHITE-SLICED-800G,198802,200401,36039
1,210102,LARGE LOAF-WHITE-UNSLICED-800G,198802,202409,56048
2,210105,LARGE WHOLEMEAL LOAF-UNSLICED,198802,200301,27161
3,210106,SIX BREAD ROLLS-WHITE/BROWN,198802,202409,65710
4,210107,"BROWN LOAF,400G,SLICED-GRAN",198903,200401,29361
...,...,...,...,...,...
1381,640233,LEISURE CENTRE MEMBERSHIP,200302,201201,17695
1382,640240,LIVERY CHARGES PER WEEK,200802,202409,20235
1383,640243,SOFT PLAY SESSION TIME PERIOD,201802,202409,9280
1384,640244,CLIMBING WALL SESSION,202202,202409,1526
1385,640406,HOTEL 1 NIGHT PRICE,200502,202409,26516

In [12]:
# load in regions data
region_df = pd.read_csv("https://eco-prices-scrapes.s3.eu-west-2.amazonaws.com/teaching/davies_price_data/db_region.csv")

region_df

,region_n,region_s,region,country,obs,p_min,p_max,p_mean,p_med,p_sd
0,1,Catalogue collections,Catalogue,NaN,306968,0.12,1999,41.329037,22.00,80.908554
1,2,London,London,England,4475848,0.01,20000,56.248341,4.60,246.010300
2,3,South East,South East,England,5785278,0.01,9499,54.609386,4.90,220.251300
3,4,South West,South West,England,3597289,0.01,6950,50.904106,4.50,201.636340
4,5,East Anglia,East Anglia,England,3204009,0.01,7650,51.067471,4.69,197.143280
5,6,East Midlands,East Midlands,England,2976879,0.01,10250,46.733604,4.07,194.929810
6,7,West Midlands,West Midlands,England,3518149,0.01,7650,43.581417,4.00,172.725430
7,8,Yorkshire & Humber,Yorkshire & Humber,England,3408323,0.01,20895,45.889851,4.29,183.482450
8,9,North West,North West,England,4294065,0.01,9310,42.274700,3.99,174.610350
9,10,North,North,England,2321737,0.01,9222,40.915108,3.99,166.738360
10,11,Wales,Wales,Wales,2216742,0.01,7347,38.699127,3.99,147.970580
11,12,Scotland,Scotland,Scotland,3385786,0.01,7999,42.445091,4.38,168.262510
12,13,Northern Ireland,Northern Ireland,Northern Ireland,1518537,0.01,6995,44.438995,5.00,163.047960

In [13]:
# merge items and prices

full_df = pd.merge(prices_df, items_df[['item_id', 'description']], on='item_id') # merge prices and items

full_df

,quote_date,shop_code,item_id_raw,region,price,indicator_box,item_id,description
0,199108.0,2.0,210101,2.0,0.49000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G
1,199007.0,10.0,210101,11.0,0.52000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G
2,199007.0,2.0,210101,12.0,0.37000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G
3,199811.0,179.0,210101,8.0,0.69000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G
4,199108.0,1.0,210101,10.0,0.47000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G
...,...,...,...,...,...,...,...,...
46689338,200704.0,441.0,640406,4.0,55.00000,NaN,640406,HOTEL 1 NIGHT PRICE
46689339,200701.0,731.0,640406,3.0,85.00000,NaN,640406,HOTEL 1 NIGHT PRICE
46689340,201210.0,5074.0,640406,3.0,40.00000,NaN,640406,HOTEL 1 NIGHT PRICE
46689341,200812.0,542.0,640406,2.0,45.00000,NaN,640406,HOTEL 1 NIGHT PRICE
46689342,202312.0,5084.0,640406,3.0,183.99001,NaN,640406,HOTEL 1 NIGHT PRICE

In [19]:
region_codes = {
    2.0: "London",
    3.0: "South East",
    4.0: "South West",
    5.0: "East Anglia",
    6.0: "East Midlands",
    7.0: "West Midlands",
    8.0: "Yorkshire & Humber",
    9.0: "North West",
    10.0: "North",
    11.0: "Wales",
    12.0: "Scotland",
    13.0: "Northern Ireland"
}

In [20]:
# add the region and country cols from the regions_df

full_df['region_name'] = full_df['region'].map(region_codes)

full_df

,quote_date,shop_code,item_id_raw,region,price,indicator_box,item_id,description,region_name
0,199108.0,2.0,210101,2.0,0.49000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G,London
1,199007.0,10.0,210101,11.0,0.52000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G,Wales
2,199007.0,2.0,210101,12.0,0.37000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G,Scotland
3,199811.0,179.0,210101,8.0,0.69000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G,Yorkshire & Humber
4,199108.0,1.0,210101,10.0,0.47000,NaN,210101,LARGE LOAF-WHITE-SLICED-800G,North
...,...,...,...,...,...,...,...,...,...
46689338,200704.0,441.0,640406,4.0,55.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South West
46689339,200701.0,731.0,640406,3.0,85.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South East
46689340,201210.0,5074.0,640406,3.0,40.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South East
46689341,200812.0,542.0,640406,2.0,45.00000,NaN,640406,HOTEL 1 NIGHT PRICE,London
46689342,202312.0,5084.0,640406,3.0,183.99001,NaN,640406,HOTEL 1 NIGHT PRICE,South East

In [22]:
items_df[items_df['description'].str.contains('hotel', case=False)]

      item_id          description  date_quote_s  date_quote_e  n_obs
1385   640406  HOTEL 1 NIGHT PRICE        200502        202409  26516

In [23]:
# restrict to only hotels

hotels_df = full_df[full_df['item_id'] == 640406]

In [24]:
hotels_df

,quote_date,shop_code,item_id_raw,region,price,indicator_box,item_id,description,region_name
46662827,201312.0,211.0,640406,8.0,38.00000,NaN,640406,HOTEL 1 NIGHT PRICE,Yorkshire & Humber
46662828,200507.0,440.0,640406,4.0,25.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South West
46662829,201103.0,378.0,640406,7.0,119.00000,NaN,640406,HOTEL 1 NIGHT PRICE,West Midlands
46662830,201904.0,15323.0,640406,5.0,65.00000,NaN,640406,HOTEL 1 NIGHT PRICE,East Anglia
46662831,200901.0,218.0,640406,5.0,75.00000,NaN,640406,HOTEL 1 NIGHT PRICE,East Anglia
...,...,...,...,...,...,...,...,...,...
46689338,200704.0,441.0,640406,4.0,55.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South West
46689339,200701.0,731.0,640406,3.0,85.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South East
46689340,201210.0,5074.0,640406,3.0,40.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South East
46689341,200812.0,542.0,640406,2.0,45.00000,NaN,640406,HOTEL 1 NIGHT PRICE,London
46689342,202312.0,5084.0,640406,3.0,183.99001,NaN,640406,HOTEL 1 NIGHT PRICE,South East

In [25]:
# change quote_date from float yyyymm to datetime

hotels_df['quote_date'] = pd.to_datetime(hotels_df['quote_date'], format='%Y%m')

hotels_df

<ipython-input-25-bdccdb43016b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotels_df['quote_date'] = pd.to_datetime(hotels_df['quote_date'], format='%Y%m')

,quote_date,shop_code,item_id_raw,region,price,indicator_box,item_id,description,region_name
46662827,2013-12-01,211.0,640406,8.0,38.00000,NaN,640406,HOTEL 1 NIGHT PRICE,Yorkshire & Humber
46662828,2005-07-01,440.0,640406,4.0,25.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South West
46662829,2011-03-01,378.0,640406,7.0,119.00000,NaN,640406,HOTEL 1 NIGHT PRICE,West Midlands
46662830,2019-04-01,15323.0,640406,5.0,65.00000,NaN,640406,HOTEL 1 NIGHT PRICE,East Anglia
46662831,2009-01-01,218.0,640406,5.0,75.00000,NaN,640406,HOTEL 1 NIGHT PRICE,East Anglia
...,...,...,...,...,...,...,...,...,...
46689338,2007-04-01,441.0,640406,4.0,55.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South West
46689339,2007-01-01,731.0,640406,3.0,85.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South East
46689340,2012-10-01,5074.0,640406,3.0,40.00000,NaN,640406,HOTEL 1 NIGHT PRICE,South East
46689341,2008-12-01,542.0,640406,2.0,45.00000,NaN,640406,HOTEL 1 NIGHT PRICE,London
46689342,2023-12-01,5084.0,640406,3.0,183.99001,NaN,640406,HOTEL 1 NIGHT PRICE,South East

FileNotFoundError: [Errno 2] No such file or directory: '/Users/gabrielmelmed/git_repos/gmelmed.github.io-1'