In [39]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import json

In [40]:

cookies = {
    'geofence_bypass': 'true'
}

response = requests.get('https://www.apartmentlist.com/research/category/data-rent-estimates', cookies=cookies)


with open("temp.html", "w") as f:
    f.write(response.text)

In [44]:
with open("temp.html", "r") as f:
    html = f.read()

soup = BeautifulSoup(html, 'html.parser')

# Find the <script> tag with id = __NEXT_DATA__
script_tag = soup.find("script", {"id": "__NEXT_DATA__"})

page_data = script_tag.text
page_data = json.loads(page_data)

with open("temp.json", "w") as f:
    f.write(json.dumps(page_data, indent=4))

file_url = page_data["props"]["pageProps"]["component"]["searchResults"][0]["fields"]["downloadableAssets"][1]["fields"]["attachment"]["fields"]["file"]["url"]

file_url

'//assets.ctfassets.net/jeox55pd4d8n/2AQ7jbgJS7X3qAmDhkMZrn/2a2aa15d23e2cd9bd38ef169ccef2d94/Apartment_List_Rent_Estimates_2024_10.csv'

In [45]:
url = "https:" + file_url

In [46]:
df = pd.read_csv(url)
df

,location_name,location_type,location_fips_code,population,state,county,metro,bed_size,2017_01,2017_02,...,2024_01,2024_02,2024_03,2024_04,2024_05,2024_06,2024_07,2024_08,2024_09,2024_10
0,United States,National,0,331097593,NaN,NaN,NaN,overall,1070.0,1071.0,...,1377,1380,1389,1397,1404,1410,1413,1412,1404,1394
1,United States,National,0,331097593,NaN,NaN,NaN,1br,940.0,941.0,...,1210,1213,1220,1227,1234,1239,1242,1240,1234,1225
2,United States,National,0,331097593,NaN,NaN,NaN,2br,1059.0,1060.0,...,1363,1366,1375,1382,1390,1396,1399,1397,1390,1380
3,California,State,6,39356104,California,NaN,NaN,overall,1741.0,1745.0,...,2112,2119,2135,2146,2154,2163,2170,2174,2168,2157
4,California,State,6,39356104,California,NaN,NaN,1br,1511.0,1515.0,...,1833,1839,1853,1863,1870,1877,1884,1887,1882,1872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475,"Oakwood, GA",City,1357260,5132,Georgia,Hall County,"Gainesville, GA",1br,NaN,NaN,...,1459,1477,1498,1507,1497,1491,1479,1464,1459,1436
3476,"Oakwood, GA",City,1357260,5132,Georgia,Hall County,"Gainesville, GA",2br,NaN,NaN,...,1342,1360,1378,1387,1378,1372,1361,1347,1343,1322
3477,"Glendale, CO",City,830340,4580,Colorado,Arapahoe County,"Denver-Aurora-Lakewood, CO",overall,1309.0,1341.0,...,1671,1683,1687,1687,1683,1706,1725,1740,1703,1665
3478,"Glendale, CO",City,830340,4580,Colorado,Arapahoe County,"Denver-Aurora-Lakewood, CO",1br,1161.0,1190.0,...,1481,1492,1496,1496,1492,1513,1530,1543,1511,1476
3479,"Glendale, CO",City,830340,4580,Colorado,Arapahoe County,"Denver-Aurora-Lakewood, CO",2br,1468.0,1505.0,...,1874,1887,1892,1892,1888,1913,1935,1951,1911,1867